name: flappy_bird_clone
description: A custom version of the Flappy Bird game built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vm_service: ^14.3.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Flappybirdy
      fonts:
        - asset: assets/fonts/FlappybirdyRegular-KaBW.ttf